import os
import time
import sqlite3
import requests
import pandas as pd
import argparse
from datetime import datetime

from tqdm import tqdm
from pathlib import Path
from InforMI import select_ionapi_file, CONFIG, get_ion_token, post_to_m3, prompt_for_company_division
from UserDefaults import load_user_defaults, save_user_defaults
from config import BASE_DIR, get_sqlite_db_path

# Configuration
ionapi_dir = Path(__file__).parent / "ionapi"
CONFIG["tenant"] = select_ionapi_file(ionapi_dir)
prompt_for_company_division()
SQLITE_DB_PATH = get_sqlite_db_path()

def process_dynamic_query(cur, table_name, sql_line, session):
    """
    Processes a single table based on the SQL string generated by the database.
    Returns the number of records loaded, or 0 if no records found.
    """
    lower_line = sql_line.lower()

    if " from " not in lower_line:
        print(f"⚠️ Skipping {table_name}: Invalid SQL format.")
        return 0

    # Split to get columns and the rest of the query
    pre_from = sql_line[:lower_line.index(" from ")]
    post_from = sql_line[lower_line.index(" from ") + 6:]

    # Determine if there's a WHERE clause
    if " where " in post_from.lower():
        table_part = post_from[:post_from.lower().index(" where ")]
        where_part = post_from[post_from.lower().index(" where "):]
    else:
        table_part, where_part = post_from, ""

    columns = [col.strip() for col in pre_from.split(",")]

    # Drop and Recreate local SQLite table
    cur.execute(f"DROP TABLE IF EXISTS {table_name}")
    create_sql = f"CREATE TABLE {table_name} ({', '.join(col + ' TEXT' for col in columns)})"
    cur.execute(create_sql)

    # Prepare M3 API payload
    source_table = table_part.strip()
    query_string = f"{','.join(columns)} from {source_table}{where_part}"

    payload = {
        "program": "EXPORTMI",
        "transactions": [{
            "transaction": "Select",
            "record": {
                "SEPC": "^",
                "HDRS": "0",
                "QERY": query_string
            },
            "selectedColumns": ["REPL"]
        }]
    }

    # API Request
    print(f"🛠️  Extracting data for: {table_name} ...")
    data = post_to_m3(payload, session)

    if not data or 'results' not in data or not data['results'][0]['records']:
        print(f"ℹ️  No records found for {table_name}.")
        return 0

    records = data['results'][0]['records']
    total = len(records)

    # Database Insert
    placeholders = ", ".join(["?"] * len(columns))
    insert_sql = f"INSERT INTO {table_name} ({', '.join(columns)}) VALUES ({placeholders})"

    with tqdm(total=total, desc=f"📥 Loading {table_name}", leave=False) as pbar:
        for record in records:
            # Split by caret and ensure we don't exceed column count
            values = record["REPL"].split("^")[:len(columns)]
            cur.execute(insert_sql, values)
            pbar.update(1)

    cur.connection.commit()
    print(f"✅ {table_name}: {total:,} records loaded")
    return total

def export_to_excel(conn, table_summary, output_path, summary_only=False):
    """
    Exports all tables to Excel with a summary sheet showing table names and record counts.

    Args:
        conn: SQLite database connection
        table_summary: List of table info dictionaries
        output_path: Path to save the Excel file
        summary_only: If True, only export the summary sheet (no detailed tabs)
    """
    print("\n📊 Exporting data to Excel...")

    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        # Create summary sheet
        summary_df = pd.DataFrame(table_summary)
        summary_df = summary_df.sort_values('Records', ascending=False)
        summary_df['Records'] = summary_df['Records'].apply(lambda x: f"{x:,}")
        summary_df.to_excel(writer, sheet_name='Summary', index=False)

        if summary_only:
            print("  ℹ️  Summary-only mode: Skipping detailed table sheets")
        else:
            # Export each table to its own sheet
            for table_info in table_summary:
                table_name = table_info['Table Name']
                try:
                    # Read table from SQLite
                    df = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)

                    # Excel sheet names are limited to 31 characters
                    sheet_name = table_name[:31]
                    df.to_excel(writer, sheet_name=sheet_name, index=False)
                    print(f"  ✓ Exported {table_name} ({len(df):,} records)")
                except Exception as e:
                    print(f"  ⚠️  Failed to export {table_name}: {e}")

    print(f"\n✅ Excel file created: {output_path}")

if __name__ == "__main__":
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Extract data from M3 and export to Excel')
    parser.add_argument('--summary-only', action='store_true',
                        help='Only create summary tab, skip detailed table sheets')
    args = parser.parse_args()

    defaults = load_user_defaults()
    save_user_defaults(defaults)

    start_time = time.time()
    token = get_ion_token()
    
    # Setup Session
    session = requests.Session()
    session.headers.update({
        "Authorization": f"Bearer {token}",
        "Accept": "application/json",
        "Content-Type": "application/json"
    })

    # The Generator Query
    generator_sql = """
    WITH LowestSequenceCols AS (
        SELECT 
            TableName, 
            ColumnName,
            MIN(sequence) -- This identifies the lowest ID (e.g., 709 vs 710)
        FROM m3TableCols
        WHERE Indexes LIKE '00%' 
        AND ColumnName NOT LIKE '%CONO'
        GROUP BY TableName
    )
    SELECT 
        a.TableName,
        GROUP_CONCAT(DISTINCT a.TableColumn) || ' from ' || a.TableName || '00 where ' || b.ColumnName || ' <> abc' AS GeneratedSQL
    FROM HerffJones_Mapping_Guide a
    LEFT JOIN LowestSequenceCols b ON b.TableName = a.TableName
    WHERE a.TableName IN (SELECT DISTINCT TableName FROM HerffJones_Mapping_Guide WHERE TableName <> '') 
    AND LOWER(a.Mapped) = 'yes'
    GROUP BY a.TableName;
    """

    with sqlite3.connect(SQLITE_DB_PATH) as conn:
        cur = conn.cursor()

        print("🔍 Fetching table mappings from SQLite...")
        cur.execute(generator_sql)
        tables_to_process = cur.fetchall()

        # Track table names and record counts for summary
        table_summary = []

        for table_name, generated_sql in tables_to_process:
            try:
                record_count = process_dynamic_query(cur, table_name, generated_sql, session)
                table_summary.append({
                    'Table Name': table_name,
                    'Records': record_count
                })
            except Exception as e:
                print(f"❌ Error processing {table_name}: {e}")
                table_summary.append({
                    'Table Name': table_name,
                    'Records': 0
                })

        # Export to Excel
        if table_summary:
            date_str = datetime.now().strftime("%Y%m%d")
            # Extract tenant name from path if it's a path
            tenant = CONFIG['tenant']
            if isinstance(tenant, Path):
                tenant_name = tenant.stem
            elif '/' in str(tenant) or '\\' in str(tenant):
                tenant_name = Path(tenant).stem
            else:
                tenant_name = str(tenant)

            company_name = CONFIG.get('company', 'Unknown')
            output_file = BASE_DIR / f"M3_Data_Export_{tenant_name}_{company_name}_{date_str}.xlsx"
            export_to_excel(conn, table_summary, output_file, summary_only=args.summary_only)

    # Timing logic
    elapsed = time.time() - start_time
    hours, rem = divmod(elapsed, 3600)
    minutes, seconds = divmod(rem, 60)
    print(f"\n✅ All tasks complete. Total run time: {int(hours):02d}:{int(minutes):02d}:{int(seconds):02d}")