SELECT 
    TRIM(CUSNAU) AS CUSNAU,
    TRIM(GRPCAU) AS GRPCAU,
    TRIM(DSEQAU) AS DSEQAU,
    TRIM(CNAMAU) AS CNAMAU,
    TRIM(LOWER(EMAIAU)) AS EMAIAU,
    TRIM(TYPEAU) AS TYPEAU
FROM PRDMODF35.AUXADR01
WHERE CONOAU = '88'
  AND GRPCAU = 'CONT1'
  AND LOWER(EMAIAU) LIKE '%@%'
  AND (CUSNAU IN (SELECT CUSN65 FROM sqlite.CML_Current) OR TYPEAU = 'V')
  