SELECT 
    TRIM(CUSNAU) AS CUSNAU,
    TRIM(GRPCAU) AS GRPCAU,
    TRIM(DSEQAU) AS DSEQAU,
    TRIM(CNAMAU) AS CNAMAU,
    TRIM(LOWER(EMAIAU)) AS EMAIAU,
    TRIM(TYPEAU) AS TYPEAU
FROM PRDMODF35.AUXADR01
WHERE CONOAU = '88'
  -- AND TYPEAU = 'V'
  AND GRPCAU = 'INVB1'
  AND LOWER(EMAIAU) LIKE '%@%'
