SELECT *
FROM (
    SELECT 
        TRIM(UPPER(PNUM35)) AS PNUM35,
        TRIM(PDES35) AS PDES35,
        TRIM(PCLS35) AS PCLS35,
        TRIM(PGMJ35) AS PGMJ35,
        TRIM(PGMN35) AS PGMN35,
        TRIM(PPUN35) AS PPUN35,
        TRIM(SUNT35) AS SUNT35,
        TRIM(TARR35) AS TARR35,
        WTSU35,
        TRIM(DSSP35) AS DSSP35,
        DTLC35,
        ROW_NUMBER() OVER (PARTITION BY TRIM(UPPER(PNUM35)) ORDER BY DTLC35 ASC) AS rn
    FROM OSL@@F3.INP35
    WHERE CONO35 = '88'
) AS Ranked
WHERE rn = 1
AND PNUM35 IN (SELECT ITNO FROM sqlite.IML_MasterItemList)
ORDER BY PNUM35, DTLC35
