SELECT DISTINCT
    TRIM(CONO50) AS CONO50,
    TRIM(ORDN50) AS ORDN50,
    CAST(TRIM(CHGC50) AS INTEGER) AS CHGC50,
    TRIM(CHGV50) AS CHGV50,
    TRIM(INVN50) AS INVN50,
    TRIM(ODES50) AS ODES50,
    CASE CAST(TRIM(CHGC50) AS INTEGER)
        WHEN 1 THEN 'UP2'
        WHEN 2 THEN 'UPN'
        WHEN 3 THEN 'UP2'
        WHEN 4 THEN 'UP3'
        WHEN 5 THEN 'UP6'
        WHEN 6 THEN 'UPN'
        WHEN 7 THEN 'UP2'
        WHEN 8 THEN 'UP3'
        WHEN 9 THEN 'UPS'
        WHEN 10 THEN 'UPS'
        WHEN 11 THEN 'UPG'
        WHEN 12 THEN 'UPG'
        WHEN 29 THEN 'FED'
        WHEN 30 THEN 'FSD'
        WHEN 31 THEN 'UP6'
        WHEN 33 THEN 'UP6'
        WHEN 35 THEN 'UP2'
        WHEN 37 THEN 'TRK'
        WHEN 38 THEN 'UP6'
        WHEN 39 THEN 'UPN'
        WHEN 40 THEN 'UP2'
        WHEN 41 THEN 'UP3'
        WHEN 43 THEN 'UPG'
        WHEN 44 THEN 'UPN'
        WHEN 45 THEN 'UP2'
        WHEN 46 THEN 'UP3'
        WHEN 50 THEN 'UP3'
        WHEN 51 THEN 'TRK'
        WHEN 52 THEN 'CPG'
        WHEN 68 THEN 'DTN'
        WHEN 69 THEN 'EST'
        WHEN 82 THEN 'DON'
        WHEN 83 THEN 'DEX'
        WHEN 84 THEN 'D2C'
        WHEN 85 THEN 'DNS'
        WHEN 90 THEN 'UXP'
        WHEN 91 THEN 'UWX'
        WHEN 92 THEN 'UXS'
        WHEN 93 THEN 'UWE'
        ELSE NULL
    END AS MODL
FROM
    S781CCD0.OSL@@F3.OEP50
WHERE
    CONO50 = '88'
    AND ORDN50 IN (SELECT DISTINCT ORDN55 FROM sqlite.OCOU_Summary)