SELECT 
    '88' AS CICONO,
    RIGHT(OH.OAORNO,7) AS CIORDN,
	--0 AS CIDESN,
    OS.UCDLIX AS CIDESN,
    OS.UCIVNO,
	7 AS CIINVN,
    JOR.CUSN40 AS CICUSN,
    JOR.DSEQ40 AS CIDSEQ,
    OS.UCSAAM AS CIIAMT,
    JOR.CURN40 AS CICURN,
    LEFT(OH.OAYREF,15) AS CIAMFU,
    '' AS CISTS
FROM [NGEUMSMI0002.D44D2F32AC81.DATABASE.WINDOWS.NET].[di_staging_prd_us].[dbo].[OOHEAD] OH
LEFT JOIN (
        SELECT UCIVNO, UCDLIX, UCORNO,  SUM(UCSAAM) UCSAAM
    FROM [NGEUMSMI0002.D44D2F32AC81.DATABASE.WINDOWS.NET].[di_staging_prd_us].[dbo].[OSBSTD]
	GROUP BY UCIVNO, UCDLIX, UCORNO
) AS OS 
    ON OH.OAORNO = OS.UCORNO
LEFT JOIN (
    SELECT ORDN40, CUSN40, DSEQ40, CURN40
    FROM [RAYMOND].[S781CCD0].[OSL@@F3].[OEP40]
) AS JOR 
    ON OH.OAYREF = JOR.ORDN40
LEFT JOIN [RAYMOND].[S781CCD0].PTFMODF35.CCINV JCC 
    ON RIGHT(OH.OAORNO,7) = JCC.CIORDN
WHERE  JCC.CIORDN IS NULL --AND COALESCE(OS.UCIVNO, '') <> ''

--!ISNULL(CIINVN) && !ISNULL(CICUSN) && CIAMFU != ""