SELECT 
	''[MESSAGE],
    'OKCONO,910,OKCUNO,' || CUNO AS KSTR,
    'OCUSMA00' AS FILE,
    'TXID' AS FLDI,
    'OSYTXH' AS TFIL,
    ROW_NUMBER() OVER (PARTITION BY CUNO ORDER BY LINO1+0) AS LINO,
    TRIM(TX60)[TX60],
    '2' AS TXEI,
    'DAIRY'[TXVR]
FROM (
	SELECT DISTINCT CUNO,TLNO30[LINO1],REPLACE(REPLACE(REPLACE(REPLACE(TRIM(TLIN30),'     ',' '),'    ',' '),'   ',' '),'  ',' ') AS TX60
	FROM SLP30
	JOIN CAML_CustomerAddressMaster ON CUSN05 = TRIM(CUSN30)
	AND LENGTH(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(TLIN30),'     ',' '),'    ',' '),'   ',' '),'  ',' ')) <= 60
	UNION
	SELECT CUNO,LINO1+0[LINO1],SUBSTR(TX60A, 1, LENGTH(TX60A) - INSTR(REVERSE(TX60A), ' ')) [TX60]
	FROM (
		SELECT DISTINCT
  			CUNO,
		    TLNO30[LINO1],
		    SUBSTR(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(TLIN30),'     ',' '),'    ',' '),'   ',' '),'  ',' '),1,60) AS TX60A
		FROM
			SLP30
		JOIN CAML_CustomerAddressMaster ON CUSN05 = TRIM(CUSN30)
		AND LENGTH(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(TLIN30),'     ',' '),'    ',' '),'   ',' '),'  ',' ')) > 60
	) AS PART1
	UNION
	SELECT CUNO,LINO1+0[LINO1],SUBSTR(TX60B, LENGTH(TX60A) - INSTR(REVERSE(TX60A), ' ') + 2) [TX60]
	FROM (
		SELECT DISTINCT
		    CUNO,
		    TLNO30 + .1 [LINO1],
		    SUBSTR(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(TLIN30),'     ',' '),'    ',' '),'   ',' '),'  ',' '),1,60) AS TX60A,
		    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(TLIN30),'     ',' '),'    ',' '),'   ',' '),'  ',' ') AS TX60B
		FROM
			SLP30
		JOIN CAML_CustomerAddressMaster ON CUSN05 = TRIM(CUSN30)
		AND LENGTH(REPLACE(REPLACE(REPLACE(REPLACE(TRIM(TLIN30),'     ',' '),'    ',' '),'   ',' '),'  ',' ')) > 60
		AND SUBSTR(TX60B, LENGTH(TX60A) - INSTR(REVERSE(TX60A), ' ') + 2) <> '***'
	) AS PART2
) AS FINAL
ORDER BY CUNO,LINO+0