SELECT * FROM (
	SELECT DISTINCT
		''[MESSAGE],
	    'OACONO,' || OACONO || ',OAORNO,' || OAORNO [KSTR],
	    'OOHEAD00' [FILE],
	    CASE WHEN USGC40 = 'I' THEN 'TXID' ELSE 'PRTX' END [FLDI],
	    'OSYTXH' [TFIL],
	    TLNO40 [LINO],
	    TLIN40 [TX60],
	    'CO01' [TXVR],
	    'GB' [LNCD],
	    CASE WHEN USGC40 = 'I' THEN '2' ELSE '1' END AS [TXEI],
	    OPTXID
	FROM INP40_O
	JOIN OOHEAD ON OAYREF = TREF40_1
	JOIN OCUSAD ON OPCUNO = OACUNO AND OPADID = OAADID
	ORDER BY KSTR,USGC40,TLNO40+0
) AS TEMP
WHERE (OPTXID = 0 and FLDI = 'PRTX') OR (FLDI = 'TXID')