SELECT DISTINCT 
''[MESSAGE],
'088'[DIVI],'105'[DONR],SUNO[PRF1],'MAIL'[MEDC],'M3_IDM_XML_CSV'[SIID],EMAIAU[TOMA],'noreply_m3@onebarnes.com'[FRMA],'ASRaymond PO-<UF01>-<UF02>-<UF03>'[SUBJ],'0'[CPPL],'1'[FIET],'CUSTOM_MAIL_TEM'[EMBT],'01'[FILM],'ASRaymond PO-<UF01>-<UF02>-<UF03>'[FNAM],'0'[PRTP]
,a.SUPN05
FROM SML_Sheet1 a
JOIN PLP05 b ON b.SUPN05 = a.SUPN05
LEFT JOIN AUXADR_CONT1 ON CUSNAU = a.SUPN05 
UNION
SELECT DISTINCT 
''[MESSAGE],
'088'[DIVI],'520'[DONR],SUNO[PRF1],'MAIL'[MEDC],'M3_IDM_XML_CSV'[SIID],BAN105[TOMA],'noreply_m3@onebarnes.com'[FRMA],'ASRaymond ACH Detail-<UF01>-<UF02>-<UF03>'[SUBJ],'0'[CPPL],'1'[FIET],'CUSTOM_MAIL_TEM'[EMBT],'01'[FILM],'ASRaymond ACH Detail-<UF01>-<UF02>-<UF03>'[FNAM],'0'[PRTP]
,a.SUPN05
FROM SML_Sheet1 a
JOIN PLP05 b ON b.SUPN05 = a.SUPN05
ORDER BY 1,2,3