SELECT
	'' AS Message,
	ORDN03 AS PUNO,
	CASE
		WHEN VCAT03 = 'SHIPPING' THEN '95'
		ELSE '90'
	END AS CDSE,
	CASE
		WHEN VCAT03 = 'SHIPPING' THEN 'TRF91'
		ELSE 'TAX91'
	END AS CEID,
	'2' AS EXTY,
	PRIC03 AS OVHE
FROM
	PMP03
WHERE
	VCAT03 IN ('SHIPPING', 'TAX')