SELECT DISTINCT 
	''[MESSAGE],
	oaorno[ORNO],
	'1'[PONR],
	'0'[POSX],
	CASE WHEN l.CATN55 = 'CA' THEN 'COC'
		 WHEN l.CATN55 = 'COC' THEN 'COC'
		 WHEN l.CATN55 = 'EXP001' THEN 'EXP001'
		 WHEN l.CATN55 = 'FIRST ARTICLE' THEN 'FAIR'
		 WHEN l.CATN55 = 'PLATING CERT' THEN 'PCERT'
		 WHEN l.CATN55 = 'PPAP LEVEL1' THEN 'PPAP'
		 WHEN l.CATN55 = 'PPAP LEVEL2' THEN 'PPAP'
		 WHEN l.CATN55 = 'PPAP LEVEL3' THEN 'PPAP'
		 WHEN l.CATN55 = 'PPAP LEVEL4' THEN 'PPAP'
		 WHEN l.CATN55 = 'QE INSP REQ''D' THEN 'QMI'
		 WHEN l.CATN55 = 'BAGGING' THEN 'TRANSP'
		 END [CRID],
	CAST(sum(CAST(l.OutstandingQty AS INTEGER)*l.UPRC55) AS TEXT)[CRAM],
	ordn40||l.ORDL55[CRD0],
	cast(l.OutstandingQty as integer)[ORQT],
	l.UPRC55[SAPR],
	''[END]
FROM OCOU_Summary l
LEFT JOIN oep40 ON ORDN40 = l.ORDN55
left JOIN OCOU_Kaller k ON k.ORDN55 = l.ORDN55 and k.ordl55 = l.ordl55
left JOIN OCOU_SOD_NEEDASRPART s ON s.ORDN55 = l.ORDN55 and s.ordl55 = l.ordl55
left join CAML_CustomerAddressMaster cam on cam.CUSN05 = CUSN40 and cam.DSEQ05 = DSEQ40 
left join oep55 o ON o.ORDN55 = l.ORDN55 and o.ordl55 = l.ordl55
left join oxhead on OAYREF = l.ORDN55
WHERE 1=1
	AND l.CATN55 IN ('CA','COC','EXP001','FIRST ARTICLE','PLATING CERT','PPAP LEVEL1','PPAP LEVEL2','PPAP LEVEL3','PPAP LEVEL4','QE INSP REQ''D','BAGGING')
	AND OAORNO is not null
GROUP BY l.CATN55,CUSO40	
ORDER BY CUSO40,l.ORDL55