SELECT * FROM (
	SELECT DISTINCT 
		''[MESSAGE],
	    'OBCONO,910,OBORNO,' || OAORNO || ',OBPONR,' || OBPONR AS KSTR,
	    'OOLINE00' AS FILE,
	    CASE WHEN USGC40 = 'I' THEN 'PRTX' ELSE 'POTX' END AS FLDI,
	    'OSYTXH' AS TFIL,
	    TLNO40[LINO],
	    TLIN40 AS TX60,
	    'CO01' AS TXVR,
	    'GB' AS LNCD,
	    CASE WHEN USGC40 = 'I' THEN '2' ELSE '1' END AS TXEI
	FROM INP40_L
	JOIN oohead on oayref = TREF40_1
	join ooline on oborno = oaorno and obcupo = CAST(SUBSTR(TREF40_2, 1, 3) AS INTEGER) 
	ORDER BY OAORNO,OBPONR
) AS TEMP