SELECT 
    ''[MESSAGE],
    'OPCONO,910,OPCUNO,' || CUNO || ',OPADRT,1,OPADID,' || ADID AS KSTR,
    'OCUSAD00' AS FILE,
    'TXID' AS FLDI,
    'OSYTXH' AS TFIL,
    LINO,
    ' ' AS TX60,
    TXVR,
    TXEI
  FROM (
		SELECT
		    CUNO,
		    SUBSTR('00000' || ADID, -5) AS ADID,
		    ROW_NUMBER() OVER (PARTITION BY CUNO,ADID ORDER BY ADID) AS LINO,
		    TLIN40 AS TX60,
		    'INTERNAL' AS TXVR,
		    '2' AS TXEI
		FROM INP40_I
		JOIN CAML_CustomerAddressMaster ON CUSN05 = TREF40_1 AND DSEQ05 = TREF40_2
		UNION
		SELECT
		    CUNO,
		    SUBSTR('00000' || ADID, -5)[ADID],
		    ROW_NUMBER() OVER (PARTITION BY CUNO,ADID ORDER BY ADID) AS LINO,
		    TLIN40 AS TX60,
		    'PICKNOTE' AS TXVR,
		  	'1' AS TXEI
		FROM INP40_E
		JOIN CAML_CustomerAddressMaster ON CUSN05 = TREF40_1 AND DSEQ05 = TREF40_2
) as part1
WHERE LINO = 1 
UNION
SELECT 
	''[MESSAGE],
    'OPCONO,910,OPCUNO,' || CUNO || ',OPADRT,1,OPADID,' || ADID AS KSTR,
    'OCUSAD00' AS FILE,
    'TXID' AS FLDI,
    'OSYTXH' AS TFIL,
    LINO+1 AS LINO,
    TX60,
    TXVR,
    TXEI
  FROM (
		SELECT
		    CUNO,
		    SUBSTR('00000' || ADID, -5) AS ADID,
		    ROW_NUMBER() OVER (PARTITION BY CUNO,ADID ORDER BY ADID) AS LINO,
		    TLIN40 AS TX60,
		    'INTERNAL' AS TXVR,
		    '2' AS TXEI
		FROM INP40_I
		JOIN CAML_CustomerAddressMaster ON CUSN05 = TREF40_1 AND DSEQ05 = TREF40_2
		UNION
		SELECT
		    CUNO,
		    SUBSTR('00000' || ADID, -5)[ADID],
		    ROW_NUMBER() OVER (PARTITION BY CUNO,ADID ORDER BY ADID) AS LINO,
		    TLIN40 AS TX60,
		    'PICKNOTE' AS TXVR,
		  	'1' AS TXEI
		FROM INP40_E
		JOIN CAML_CustomerAddressMaster ON CUSN05 = TREF40_1 AND DSEQ05 = TREF40_2
) as part2
ORDER BY KSTR,LINO,TXEI
